site_name: 2023_CO

theme:
  name: material
  palette:
    scheme: slate
  language: zh
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search
repo_url: https://github.com/guahao31/2023_CO
repo_name: 2023_CO

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Warm Up:
    - Vivado 安装: warmup/Vivado_installation.md
    - Lab0: warmup/Lab0.md
  - Lab1: 
    - Lab1/Lab1.md
    - ALU: Lab1/ALU_RegFile/ALU.md
    - RegFile: Lab1/ALU_RegFile/RegFile.md
    - FSM: Lab1/FSM/FSM.md
  - Lab2: 
    - Lab2/Lab2.md

  - Other:
    - Git 基础: Other/about_git.md

